### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by Braveras** [KaironShadowfall/Discordjs-Slash-Command-Handler#1]
Would it be possible to have multi-language support based on strings instead of google translator api?

**Comment by KaironShadowfall** [comment]
Yes, it is possible to have multi-language support based on strings instead of the Google Translate API, you can replace the `translation` function in `src/events/guild/interactionCreate.js` at line `40` with this code:

```js
const lang = langCodes.includes(langDB.get(`language.${interaction.guild.id}`)) ? langDB.get(`language.${interaction.guild.id}`) : "en";
const language = require("./path/to/language/${lang}.json");
translation = language;
```

If this is what you meant, I hope I answered your question correctly.

**Comment by Braveras** [comment]
yes this is what i meant, thanks for answering!
